module_separator = " "

[bookmarks]
search_depth = 100
exclude = []

[[module]]
type = "Symbol"
symbol = "ðŸ¥‹"
color = "Blue"

[[module]]
type = "Bookmarks"
separator = " "
color = "Magenta"
behind_symbol = "â‡¡"

[[module]]
type = "Commit"
max_length = 6
color = "White"
empty_text = "(empty)"

[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = "ðŸ’¥"
color = "Red"

[module.divergent]
disabled = false
text = "ðŸš§"
color = "Yellow"

[module.empty]
disabled = false
text = ""
color = "Yellow"

[module.immutable]
disabled = false
text = "ðŸ”’"
color = "Yellow"

[module.hidden]
disabled = false
text = "ðŸ‘»"
color = "Yellow"

[[module]]
type = "Metrics"
template = "[{changed} {added}{removed}]"
color = "Blue"

[module.changed_files]
prefix = ""
suffix = ""
color = "Cyan"

[module.added_lines]
prefix = "+"
suffix = ""
color = "Green"

[module.removed_lines]
prefix = "-"
suffix = ""
color = "Red"
